### ISSUE TITLE
Add eslint-plugin-react-hooks

### ISSUE THREAD

**Issue by ALapina** [ALapina/Weather-app-Challenge#18]
## Short Summary

I need to work more with npm and learn how to add and customize additional eslint plugins.
Install eslint-plugin-react-hooks for local and CI use.
https://www.npmjs.com/package/eslint-plugin-react-hooks#installation

## Definition of Done

eslint-plugin-react-hooks is installed and working locally and with CI

**Comment by aalekseev** [comment]
@ALapina please take this as a priority so we can finalize project setup milestone

**Comment by ALapina** [comment]
This plugin is included by default in Create React App! 
https://reactjs.org/docs/hooks-rules.html#eslint-plugin
