### ISSUE TITLE
Setup initial styles

### ISSUE THREAD

**Issue by aalekseev** [ALapina/Weather-app-Challenge#2]
## Short Summary

Before starting new Frontend development, let's setup basic styles and select used technologies

## Definition of Done

- Provided Figma design analyzed for brand colors, spacing and fonts
- These things putted into CSS variables as base for design system
- We selected and added tech stack for working with styles. Some options:
    - Pure CSS
    - CSS modules
    - Styled components
    - Sass
    - TailwindCSS
    - Bootstrap

**Comment by ALapina** [comment]
styled components
css color variables (themes) https://styled-components.com/docs/advanced#theming
font family and weight (Raleway)
global styles https://scalablecss.com/styled-components-global-styles/
styled-normalize https://github.com/sergeysova/styled-normalize
